news_sites:
  vanguardia:
    url: https://www.vanguardia.com
    queries:
      homepage_article_links: '.article.element.no-access.restricted a'
      article_summary: 'headline.font-1.bold.mainheadlineart'
      article_title: 'subheadline.font-1.bold.lead'
  elespectador:
    url: https://www.elespectador.com
    queries:
      homepage_article_links: '.Card-Title a'
      article_summary: '.Hook.ArticleHeader-Hook.Hook_main div'
      article_title: '.Title.ArticleHeader-Title.Title_article'

